travis:
  secure:
    BINSTAR_TOKEN: ryIhc/1gPps5X8BND8qR9CScwMZw7OCkO3uBg7bF9MoMBXpQBU9n7m4pflNKwUbQWZKYQURbBIs2sb/U+NThpZMRaKLCepyZwK4Iocv8nFMSrcH6t7er7ptKYZP5Z51qaZ+znuqDccR7xx4F59/uwrN5OtkzNMUCjaNwxcLb1xtaLKVWvAOPCMKXvVY4SEk9dpfhvsIr0rYNnxUBhxryrW+Vmc9BNAcwPvBayDMrCbEeUau32+KZtISCr0j/3441GbcLjW807tx7rWZKTytcthNv3Qt4wp2gax7iD7aLm4XAKvjR+wHa++dcC3EYWWr7Af4WMyFEj9W0VHAXtgAlMWW3FMhgmPDb+v4V1CUigftrghTk8aFsm1LbcxB4W1ASTdpnkg1nzil/xevOSab1xZyvRALa9xIMLxQx32CNOj0TV+x2MCQ0WdC14n52o6KOBDbGyFw9BtmnP4sPWcL2vnV/KIWLzPlfr5HMUcQjQrkY6G5mWuoaco3WN14XYBunapO9D+uBEudKeGeVofGX3Mms1TAye0Gt7vgKR5x9CWMnrEYTNhpEIc2QcS71R9iJTA/aXyxZRx/U7WgL+wU7LeFpCw2533evbAaiDHWHCouNAya/hRV1b9TdFSiVw1ViGCip9OQUqoVPeCOKMhmLrf01/wDbXIx1r/JR7VWTy94=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
